name: clang-format check

on:
  push:
    paths:
      - "**/*.c"
      - "**/*.cpp"
      - "**/*.h"
      - "**/*.hpp"
      - ".clang-format"
      - ".github/workflows/clang-format-check.yml"
  pull_request:
    paths:
      - "**/*.c"
      - "**/*.cpp"
      - "**/*.h"
      - "**/*.hpp"
      - ".clang-format"
      - ".github/workflows/clang-format-check.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Check C and C++ formatting
        uses: jidicula/clang-format-action@654a770daa28443dd111d133e4083e21c1075674 # v4.18.0
        with:
          clang-format-version: "22"
          check-path: "."
          exclude-regex: "/(components|managed_components|build|main/hal/drivers)/"
